AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Trigger lambda with upload to S3
Resources:
  S3Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: s3-lambda.handler
      Runtime: nodejs6.10
      Policies: AmazonS3ReadOnlyAccess
      Events:
        DataUpload:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
      Timeout: 15
      MemorySize: 300

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambda-workshop-s3